codes = {
    'ncic': {
        'colors': {
            'AME': 'Amethyst Purple',
            'BGE': 'Beige',
            'BLK': 'Black',
            'BLU': 'Blue',
            'BRO': 'Brown',
            'BRZ': 'Bronze',
            'CAM': 'Camouflage',
            'COM': 'Chrome',
            'CPR': 'Copper',
            'CRM': 'Cream',
            'DBL': 'Dark Blue',
            'DGR': 'Dark Green',
            'GLD': 'Gold',
            'GRN': 'Green',
            'GRY': 'Gray',
            'LAV': 'Lavender Purple',
            'LBL': 'Light Blue',
            'LGR': 'Light Green',
            'MAR': 'Maroon',
            'MVE': 'Mauve',
            'ONG': 'Orange',
            'PLE': 'Purple',
            'PNK': 'Pink',
            'RED': 'Red',
            'SIL': 'Silver',
            'TAN': 'Tan',
            'TEA': 'Teal',
            'TPE': 'Taupe',
            'TRQ': 'Turquoise',
            'WHI': 'White',
            'YEL': 'Yellow',
        },
        'makes': {
            'ACUR': 'Acura',
            'AUDI': 'Audi',
            'BMW': 'BMW',
            'BUIC': 'Buick',
            'CADI': 'Cadillac',
            'CHEV': 'Chevrolet',
            'CHRY': 'Chrysler',
            'DODG': 'Dodge',
            'FORD': 'Ford',
            'GMC': 'GMC',
            'HOND': 'Honda',
            'HYUN': 'Hyundai',
            'INFI': 'Infiniti',
            'ISU': 'Isuzu',
            'JAGU': 'Jaguar',
            'JEEP': 'Jeep',
            'KIA': 'Kia',
            'LEXS': 'Lexus',
            'LINC': 'Lincoln',
            'MAZD': 'Mazda',
            'MITS': 'Mitsubishi',
            'NISS': 'Nissan',
            'PONI': 'Pontiac',
            'PONT': 'Pontiac',
            'STRN': 'Saturn',
            'SUBA': 'Subaru',
            'SUZI': 'Suzuki',
            'TOYT': 'Toyota',
            'VOLK': 'Volkswagen',
            'VOLV': 'Volvo',
        },
        'types': {
            '0B': 'Omnibus',
            '0R': 'Organization',
            'AM': 'Ambulance',
            'AP': 'Apportioned',
            'AQ': 'Antique',
            'AR': 'Amateur Radio',
            'AT': 'All-Terrain Vehicle',
            'BU': 'Bus',
            'C0': 'Commercial',
            'CC': 'Consular Corps',
            'CI': 'City-Owned',
            'CL': 'Collegiate',
            'CM': 'Commemorative',
            'CN': 'Conservation',
            'CU': 'County-Owned',
            'DA': 'Drive Away',
            'DB': 'Dune Buggy',
            'DL': 'Dealer',
            'DP': 'Diplomatic',
            'DU': 'Duplicate',
            'DV': 'Disabled Veteran',
            'DX': 'Disabled Persons',
            'EX': 'Exempt',
            'FD': 'Fire Department',
            'FM': 'Farm Vehicle',
            'HI': 'Hearing Impaired',
            'IP': 'International Plate',
            'IT': 'In-Transit (Temporary)',
            'JJ': 'Judge or Justice',
            'LE': 'Legislative',
            'LF': 'Law Enforcement',
            'MC': 'Motorcycle',
            'MD': 'Motorcycle Dealer',
            'MF': 'Manufacturer',
            'ML': 'Military Vehicle (Canadian)',
            'MP': 'Moped',
            'MR': 'Armed Forces Reservist',
            'MV': 'Military Vehicle (US)',
            'MY': 'Military (Aircraft)',
            'NG': 'National Guard',
            'NP': 'Non-Passenger Civilian Aircraft',
            'PC': 'Passenger Car',
            'PE': 'Personalized/Customized',
            'PF': 'Professions',
            'PH': 'Doctor',
            'PP': 'Passenger Civilian Aircraft',
            'PR': 'Press',
            'PS': 'Professional Sports Team',
            'PX': 'Pharmacist',
            'RE': 'Reciprocal',
            'RV': 'Rented Vehicle or Trailer',
            'SC': 'Special Purpose',
            'SN': 'Snowmobile',
            'ST': 'State-Owned',
            'SV': 'School Vehicle',
            'TK': 'Truck',
            'TL': 'Trailer',
            'TM': 'Temporary',
            'TP': 'Transporter',
            'TR': 'Semi-truck',
            'TX': 'Taxi Cab',
            'US': 'US Government',
            'VF': 'Veteran',
            'ZZ': 'ATV and Snowmobiles',
        }
    }
}
